name:                EnclaveIFC
version:             0.1.0.0
github:              "Abhiroop/EnclaveIFC"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Abhiroop/EnclaveIFC#readme>

dependencies:
- base >= 4.7 && < 5

flags:
  enclave:
    manual: true
    default: false

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

# library doesn't require the flag
library:
  source-dirs: src
  dependencies:
    - binary
    - bytestring >= 0.11
    - network-simple
    - transformers
  when:
    - condition: (flag(enclave))
      then:
        cpp-options: -DENCLAVE
      else:
        cpp-options: -DUMMY

executables:
  EnclaveIFC-exe:
    main:                Main.hs
    source-dirs:         app
    when:
    - condition: (flag(enclave))
      then:
        cpp-options: -DENCLAVE
      else:
        cpp-options: -DUMMY

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EnclaveIFC
    - binary
    - bytestring >= 0.11
    - network-simple
    - transformers

tests:
  EnclaveIFC-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EnclaveIFC
